#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2018-07-04 周三 11:27
#+TITLE: anki deck production
#+DESCRIPTION: 
#+TAGS: anki, deck, subs2srs, aboboo, MKVExtractGUI2, SrtEdit, ASChange, speed
#+CATEGORIES: soft
#+EXTRA-YAML-HEADERS: theme: \nplugin: \nscheme-text: "#ffffff"\nscheme-link: "#ff8540"\nscheme-hover: "#"\nscheme-code: "#"\nscheme-bg: "#6b1606"\nscheme-hero-text: "#8d3700"\nscheme-hero-link: "#ee4000"\nscheme-hero-bg: "#ffb580"\n


* Download *.mkv film or U.S.drama
* MKVExtractGUI2
a. Download mkvtoolnix-20-0-0-64-bit, the latest version is 23rd, what we need is 20th here.
Installed 
b. Download MKVExtractGUI2, the latest version is 2.4.0.0, what we need is 1.6.4.1 here.
put MKVExtractGUI2 into mkvtoolnix's installation folder.
c. Use MKVExtractGUI2 to seperate *.mkv into video, music, and subtitle files.
d. Use mkvtoolnix to combine video and music files into a new *.mkv file.
* Use SrtEdit to convert subtitle file and adjust the timeline.
* aboboo
a. Add *mkv file, load subtitles, remove short sentence. Save original and translated subtitles in *srt UTF-8 format seperately.
b. (You can also make aboboo mobile courseware.[1])
* subs2srs
a. Subs1, Original subtitle; Subs2, translated; Check the Normalize Audio box; modify Generalte Audio Clips into 320, modify Generate Snapshots and Video Clips into best quality; modify Bitrates into 3200 and 320 kb/s; Name of deck as XX.S01, and E01 is defined by First Episode. Now you can preview it.
b. The generated files is in the Output folder. The *.mp3.
* anki
a. First, you need modify the **.S01.tsv‘s contents,remove the first =Tab= symbol for each line.
b. Open anki, =Import File=
c. Type is subs2srs, Deck is U.S.drama::[Yours deck's name]::espode number, and =Import= it.
* ASChange
a. add all mp3 files, select all, hit =Convert=
b. =Format= tag, Max. Quality; =Extras= tag, Don't check =Normalize volume= box, if you had adjusted th volume by check the =Normalize Audio= option in =subs2srs=.

[1] I'll write a other tutorial.
