#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-08-23 二 17:12
#+TITLE: pc change rec
#+DESCRIPTION: 日常修改的记录
#+TAGS: pc,修改,记录
#+CATEGORIES: mobile

* <2018-04-10 二>
** How to execute command on startup (rc.local alternative) 
 which involves use of systemd here:
***    Create a service:
#+BEGIN_SRC 
    sudo vi /etc/systemd/system/rc-local.service
#+END_SRC
***    Add your code there:
#+BEGIN_SRC 
    [Unit]
    Description=/etc/rc.local Compatibility
    ConditionPathExists=/etc/rc.local

    [Service]
    Type=forking
    ExecStart=/etc/rc.local start
    TimeoutSec=0
    StandardOutput=tty
    RemainAfterExit=yes
    SysVStartPriority=99

    [Install]
    WantedBy=multi-user.target
#+END_SRC
***    Create and make sure /etc/rc.local is executable and add this code inside it:
#+BEGIN_SRC 
        sudo chmod +x /etc/rc.local
#+END_SRC
#+BEGIN_SRC 
    #!/bin/sh -e
    #
    # rc.local
    #
    # This script is executed at the end of each multiuser runlevel.
    # Make sure that the script will "exit 0" on success or any other
    # value on error.
    #
    # In order to enable or disable this script just change the execution
    # bits.
    #
    # By default this script does nothing.

    exit 0
#+END_SRC
***    Enable the service:
#+BEGIN_SRC 
    sudo systemctl enable rc-local
#+END_SRC
***    Start service and check status:
#+BEGIN_SRC 
    sudo systemctl start rc-local.service
    sudo systemctl status rc-local.service

#+END_SRC

    If all goes well you can add your code to the /etc/rc.local file then restart it.

** openbox close sleep and screensaver
#+BEGIN_SRC 

#xset s 300      #设置屏保时间为300秒，时间单位为秒
#xset s 0        #关闭屏幕保护
#xset dpms 0 0 0 # 三个数值分别为Standby、Suspend、Off，单位秒
#xset -dpms      #关闭电源管理

#+END_SRC
** openbox environment setup
Setting up your environment

If you would like to set environment variables that will affect everything run in your current session (including Openbox), you can place them in ~/.config/openbox/environment. Here's an example ~/.config/openbox/environment file:
#+BEGIN_SRC 
# Set up my own path
export PATH=$HOME/bin:$PATH

# Change the language used from the system's default
export LC_CTYPE=ja_JP.utf8

# SCIM for typing non-english characters
export XMODIFIERS=@im=SCIM
export GTK_IM_MODULE=scim
export QT_IM_MODULE=scim
#+END_SRC

** openbox keyblinding setup, ~/.config/openbox/rc.xml
#+BEGIN_SRC 
    <!-- Keybindings for running applications -->
    <keybind key="W-e">
      <action name="Execute">
        <startupnotify>
          <enabled>true</enabled>
          <name>kfmclient</name>
        </startupnotify>
        <command>pcmanfm</command>
      </action>
    </keybind>
#+END_SRC

* <2017-06-01 四>
chane the _app/assets/themes/curtana/_less/common.less
table {

tr:nth-child(even){background-color: #f5f2ff}

th {
    background-color: #cC0Ff0;
    color: white;
}
     // TODO: responsive table support
-    // display: inline-block;
-    // overflow-x: auto;
-    // white-space: nowrap;
+    display: inline-block;
+    overflow-x: auto;
+    white-space: nowrap;
}
and then the TABLE had 横拉滚动条
* <2017-04-14 五>
A friend sent me an email with a JPEG photo in the middle of the text. The picture is so big, most of it is outside the screen and I want to view it with an outside image viewer and not in Gnus. How do I save an image that is included in the email in Gnus, if it's not just an ordinary attachment?

The command you need is gnus-summary-save-parts. You have an inline image, which implies that you received an HTML mail. An inline image is an instance of a so-called MIME part, where MIME is an Internet standard governing email-related things such as non-text attachments.

L ;;list all group of gnus
X m ;;save image to ~/

debian chrome extensions installation is not enabled.
se /etc/environment
CHROMIUM_FLAGS='--enable-remote-extensions'

* <2017-04-13 四>
export WINEARCH=win32
export WINEPREFIX=$HOME/.mynewwine32prefix/

bash winetricks dotnet30
proxychains4 bash winetricks dotnet40

wget kegel.com/wine/winetricks && sh winetricks ie8 ;;this is too old.

emacs: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
https://packages.debian.org/jessie/libpng12-0
s dpkg -i lib*
s apt-get install -f

* <2017-03-02 四>
install wine-qq on debian
http://www.longene.org/forum/viewtopic.php?f=6&t=30516

* <2017-01-24 二>
change emacs' color in terminator, add this line to .bashrc
export TERM=xterm-256color

define terminator's default position, change the '.local/share/applications/terminator.desktop' to:
terminator --geometry=1200x900+0+0

add the font of msyh.ttf

define the font by #gnome-tweak-tool

* <2016-12-19 一>
#spni -g n ;; to install npm's extension n
#s n 7.2.1 ;;to install nodejs v7.2.1

* <2016-08-23 二>
.emacs
L625
  (setq myvar/relative-filename (concat "http://yefeiyu.github.io/assets/img/" myvar/img-name))
* <2016-08-25 四>
sudo apt-get install bleachbit
sudo apt-get install sweeper 
sudo apt-get remove sweeper
sudo dpkg -i nautilus_nutstore_amd64.deb 
<2016-09-21 三>
install vmware debian and windows xp.
debian:
sai xfce4
add 6 keyboads shortcut, such as emacs, conkeror, gnus
change the desktop to 600x800, which need change the VGA1 to Virtual1
rehook dropbox to /home/xx/Dropbox
change conkerorrc's qiushi to 98%, and //.

eba
alias gl='git pull'
